### ISSUE TITLE
Sprint 1 | User On-boarding | Login and Registration

### ISSUE THREAD

**Issue by glind** [TransparentPath/buildly-core#1]
Login and Registration sections in the React Template should be connected to Buildly Core and allow for new registrations (with admin approval) and login as an Admin, Producer and View Only

- [x] https://github.com/TransparentPath/buildly-react-template/issues/6
- [x] https://github.com/TransparentPath/buildly-react-template/issues/5
- [ ] https://github.com/TransparentPath/buildly-core/issues/2 Reset Password
- [ ] https://github.com/TransparentPath/buildly-react-template/issues/21 Documentation

**Comment by prabhleen-kaur-hub** [comment]
Stories associated:
1. Register: https://github.com/TransparentPath/buildly-react-template/issues/5
2. Login: https://github.com/TransparentPath/buildly-react-template/issues/6
