### ISSUE TITLE
Sprint 2 | Gateways 

### ISSUE THREAD

**Issue by prabhleen-kaur-hub** [TransparentPath/buildly-core#14]
Gateways is the screen dealing with the following operations:
Add
Delete
Edit
Tabular representation.

**Description:**
This is the last option along with sensors in the dashboard 
It will display the list of items with the following columns for GATEWAY
     1.1 UUID
     1.2 Alias 
     1.3 Gateway type
     1.4  Battery 
     1.5 Shipment 
     1.6 Activated 
     1.7 Associated with gateway 
     1.8 Edit: Users can edit the information. 
     1.9 Delete: The user can delete the row. 

**Associated stories:**
Add Gateway:
- [x] https://github.com/TransparentPath/buildly-core/issues/12

Edit/Delete: 
- [x] https://github.com/TransparentPath/buildly-core/issues/13

**Comment by prabhleen-kaur-hub** [comment]
Feedback: June 26, 2020
Gateways / Sensors 
- [ ] Cross docking / segments need to be defined – where shipments can be split at each custody.

**Comment by prabhleen-kaur-hub** [comment]
Feedback: July 8, 2020
Gateway & Sensor View

- [ ] Error adding Gateway
- [ ] For 'Add Sensor', Sensor Placed - is this for where the sensor is placed on the pallet, shipment, etc. or the location where the sensor is placed?
- [ ] After associating a gateway to a sensor and clicking on 'Add Sensor', get an 'Error in creating Gateway' message.
