### ISSUE TITLE
Sprint 1 | Custodians 

### ISSUE THREAD

**Issue by prabhleen-kaur-hub** [TransparentPath/buildly-core#3]
Custodian is the screen dealing with the following operations: 
1. Add 
2. Delete 
3. Edit 
4. Tabular representation. 

**Description:** 
1. This is the forth menu option out of 5. 
2. It will display the list of custodians with the following columns: 
     2.1 Custodian Name
     2.2 Custodian ID 
     2.3 location 
     2.4 GLN
     2.5 Current shipment 
     2.6 Associated shipment  
     2.7 Edit: Users can edit the information. 
     2.8 Delete: The user can delete the row. 

**Associated stories:** 
1. Add custodian: 
- [x] https://github.com/TransparentPath/buildly-core/issues/4

2. Edit/Delete 
- [x] https://github.com/TransparentPath/buildly-core/issues/5

**Comment by prabhleen-kaur-hub** [comment]
Note by @karrla https://github.com/orgs/TransparentPath/projects/3#card-38967927

**Comment by prabhleen-kaur-hub** [comment]
Feedback: July 8, 2020
Custodian View

- [ ] Need an explanation of an Alias. Should this be greyed out for Pilot2? Similar for other fields such as Consortium, GLN, etc.
- [ ] Should we require all the contact address - city, zip code, etc to be mandatory rather than some.?
