### ISSUE TITLE
Sprint 2 | Items 

### ISSUE THREAD

**Issue by prabhleen-kaur-hub** [TransparentPath/buildly-core#7]
Items is the screen dealing with the following operations:
Add
Delete
Edit
Tabular representation.

**Description:**
1. This is the third option out of 7. 
2. It will display the list of items with the following columns: 
    2.1 Item ID
    2.2 Item description  
    2.3 Number of units 
    2.4 Item Type
    2.5 Shipping ID 
    2.6 Value
    2.7 Add to shipment 
    2.8 Edit: Users can edit the information. 
    2.9 Delete: The user can delete the row. 

**Associated stories:**
Add Items: 
- [x] https://github.com/TransparentPath/buildly-core/issues/8

Edit/Delete
- [x] https://github.com/TransparentPath/buildly-core/issues/9

**Comment by prabhleen-kaur-hub** [comment]
Feedback: June 26, 2020
Items 
- [ ] Items get added to the top rather than underneath the previous item in the list. 
- [ ] Can Items Description be imported from customer’s file 
Comment by @glind We need to look at a simple CSV import at least from the backend for Item Inventory
- [ ] Need to add Unit of Measure table 
- [ ] After adding some of the fields, they don’t get populated on the Items View 
- [ ] Editing items removes items that were originally included 
- [ ] Deleting items works.

**Comment by prabhleen-kaur-hub** [comment]
Feedback: July 8, 2020
Items View

- [ ] In 'Add Items', the number of units have an up down arrow.
- [ ] For 'Units of Measure' and other similar drop downs, need to update the database with proper values.
- [ ] 'Item Description' doesn't get saved on the main Items view page when changed. Is it needed?
